<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BDoc</RootNamespace>
    <AssemblyName>BDoc</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="HtmlToOpenXml.dll" Version="3.4.1" />
    <PackageReference Include="AngleSharp" Version="1.5.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="BDoc.Application\BDoc.Application.csproj" />
    <ProjectReference Include="BDoc.Domain\BDoc.Domain.csproj" />
    <ProjectReference Include="BDoc.Infrastructure\BDoc.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="BDoc.Domain\**;BDoc.Application\**;BDoc.Infrastructure\**" />
  </ItemGroup>

</Project>